const express = require('express');
const { getAllQuestionController, createQuestionController, getQuestionByIdController, updateQuestionController, deleteQuestionController, uploadQuestionImageController, uploadQuestionOptionController, uploadQuestionExplanationController,} = require('../controller/questionController');
const router = express.Router();
const { createQuestionValidationRules, getQuestionValidationRules, updateQuestionValidationRules, deleteQuestionValidationRules } = require('../validator/questionValidator');
const createUpload = require('../config/multer');
router.get('/',getAllQuestionController);
router.post('/',createQuestionValidationRules,createQuestionController);
router.get('/:id',getQuestionValidationRules,getQuestionByIdController);
router.put('/:id',updateQuestionValidationRules,updateQuestionController);
router.delete('/:id',deleteQuestionValidationRules,deleteQuestionController);
router.post('/upload/question-image',createUpload("questions").single('que-img'),uploadQuestionImageController);
router.post('/upload/question-option',createUpload("options").single('opt-img'),uploadQuestionOptionController);
router.post('/upload/question-explanation',createUpload("explanations").single('exp-img'),uploadQuestionExplanationController);
module.exports = router;